name: Docker to Ec2 Series Builds
on:
  push:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login to Dockerhub registry
        run: | 
          docker login -u shahabfaderani -p "${{secrets.DOCKER_PASSWORD}}"
      
      - name: docker build backend
        working-directory: ./backend
        run: |
          docker build -t announcement_board_backend .
          
      - name: tagging the docker build
        run: |
          docker tag announcement_board_backend shahabfaderani/announcement_board_backend:0 
          
      - name: docker push
        env: 
          DOCKER_USER_NAME: shahabfaderani
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: | 
          docker push docker.io/shahabfaderani/announcement_board_backend:0
