name: Docker to Ec2 Series Builds
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: docker login
        env: 
          DOCKER_USER_NAME: ${{secrets.DOCKER_USER_NAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo $DOCKER_USER_NAME
          echo $DOCKER_PASSWORD
          docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
      - name: docker build backend
        run: |
          docker build -t shahabfaderani/announcement_board_backend:LIVE .

