name: Docker to Ec2 Series Builds
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login to Dockerhub registry
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USER_NAME}}" --password-stdin  
        
      - name: login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: docker build backend
        run: |
          docker build --file ./backend/Dockerfile -t announcement_board_backend .
          
      - name: tagging the docker build
        run: |
          docker tag announcement_board_backend shahabfaderani/announcement_board_backend:0 
          
      - name: docker push
        run: | 
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{secrets.DOCKER_USER_NAME}} --password-stdin
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.io -u ${{secrets.DOCKER_USER_NAME}} --password-stdin
          docker push docker.io/shahabfaderani/announcement_board_backend:0

