name: Docker to Ec2 Series Builds
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: docker build backend
        run: |
          docker build --file ./backend/Dockerfile -t shahabfaderani/announcement_board:BACKEND .
      - name: docker login and push backend
        env: 
          DOCKER_USER_NAME: ${{secrets.DOCKER_USER_NAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker logout
          docker login -u "$DOCKER_USER_NAME" -p "$DOCKER_PASSWORD"
          docker push shahabfaderani/announcement_board:BACKEND   

