name: Docker to Ec2 Series Builds
on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    #dd
    steps:
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2

        with:
          username: shahabfaderani
          password: Alivasei123
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: shahabfaderani/announcement_board_backend:latest
      
    
